-- DATABASE COMMANDS 
CREATE DATABASE WINGSOFFIRE;
USE WINGSOFFIRE;
SELECT DATABASE();

USE SAKILA;
SELECT DATABASE();

-- FETCH STATIC VALUES 
SELECT 'TODAY IS A LOVELY DAY';
-- USER DEFINED COLUMN HEADING
SELECT 'TODAY IS A LOVELY DAY' AS 'MESSAGE';
SELECT 100 + 200;
SELECT 100 + 200 AS 'TOTAL';

-- INBUILT ARITHMETIC FUNCTIONS IN MYSQL
-- SELECT <FUNCTIONANME>(<PARAMETERS, PARAMETERS>); 
SELECT PI();
SELECT TRUNCATE(1234,1);
SELECT TRUNCATE(1234,-1);
SELECT TRUNCATE(1234,0);
SELECT TRUNCATE(-1234,1);
SELECT TRUNCATE(-1234,-1);
SELECT TRUNCATE(-1234,0);
SELECT SQRT(25);

-- FETCH RECORDS FROM TABLE
SELECT * FROM ACTOR;
SELECT * FROM SAKILA.ACTOR;

-- SORT ORDER
SELECT * FROM ACTOR ORDER BY FIRST_NAME;
SELECT * FROM ACTOR ORDER BY FIRST_NAME ASC;
SELECT * FROM ACTOR ORDER BY FIRST_NAME DESC;
SELECT * FROM ACTOR ORDER BY 2 ASC;
SELECT * FROM ACTOR ORDER BY 3 DESC;

-- FILTER COLUMNS
SELECT FIRST_NAME, LAST_NAME FROM ACTOR;
SELECT LAST_NAME, FIRST_NAME FROM ACTOR;

-- FILTER ROWS
SELECT FIRST_NAME, LAST_NAME FROM ACTOR WHERE FIRST_NAME = 'WOODY';
SELECT FIRST_NAME, LAST_NAME FROM ACTOR WHERE FIRST_NAME = 'WOODY' AND LAST_NAME = 'JOLIE';
SELECT * FROM ACTOR WHERE ACTOR_ID > 100;

-- IP WIRTE A QUERY TO SORT LIKE THE GIVEN BELOW
-- ADAM HOPPER
-- ADAM GRANT
-- BEN WILLIS
-- BEN HARRIS

-- EMPTY RESULT SET
SELECT * FROM ACTOR WHERE FALSE;
-- IP FIND AN ALTERNATE METHOD TO ACHEIVE THE SAME RESULT

-- AGGREGATE FUNCTIONS
SELECT COUNT(*) FROM ACTOR;
SELECT * FROM ACTOR;
